url: https://arbosteun.github.io/en
#baseurl: /arbosteun/

# Site settings
title:
  en: ErGo-knowhow
  nl: ErGo-knowhow (voorheen Arbosteun)
header_services:
  en: Services
  nl: Diensten
header_portfolio:
  en: Client Portfolio
  nl: Klant Portfolio
header_about:
  en: About ErGo-knowhow
  nl: Over ErGo-knowhow
header_contact:
  en: Contact
  nl: Contact

index: en/index.html  

email: ilyaslingerland@arbosteun.nl
description: "Arbosteun levert adviesdiensten op het gebied van arbeidsomstandigheden binnen bedrijven door heel Europa. Deze adviesdiensten variëren van ergonomische adviezen ter voorkoming van lichamelijke klachten, tot het uitvoeren van Risico Inventarisaties en -Evaluaties.
Door Arbosteun klein te houden is de aanpak persoonlijker en kunnen we zodoende meer maatwerk leveren. Dit brengt onze dienstverlening naar een hoger niveau. Wij komen graag bij u langs om vrijblijvend kennis te maken!"

# Team names, titles and social links
people:

- name: Ilya Slingerland-den Dulk
  pic: 1
  position: Ergonomic Expert
#  social:
#    - title: linkedin
#      url: http://linkedin.com/ilyaslingerland

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: linkedin
#    url: http://linkedin/ilyaslingerland

# Postal address (add as many lines as necessary)
address:
  - line: Simon Gammerkade 1,
  - line: 1544 VL, Zaandijk
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty

